name: socket
version: 0.0.1
author: penlook
description: Penlook Frontend Application
environment:
    sdk: '>=1.0.0 <2.0.0'
dependencies:
    shadow_dom: any
dev_dependencies:
    browser: any
    unittest: any
